# Generated by Django 3.2.9 on 2021-11-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20211120_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='ytube_playlist_plid',
            new_name='ytube_pl_ID',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='ytube_playlist_url',
            new_name='ytube_pl_URL',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='ytube_url',
            new_name='ytube_vi_URL',
        ),
        migrations.AlterField(
            model_name='video',
            name='category_id',
            field=models.IntegerField(choices=[(1, 'HTML/CSS'), (2, 'JavaScript'), (3, 'Python'), (4, 'Django'), (5, 'Salsa'), (6, 'RKW')]),
        ),
    ]
